trigger:
  branches:
    include:
      - main

variables:
  dockerRegistryServiceConnection: 'acrproductservice' # ACR service connection
  imageRepository: 'product-service'
  containerRegistry: 'acrsringbootapp1.azurecr.io'
  dockerImage: '$(containerRegistry)/$(imageRepository):$(Build.BuildId)'
  azureSubscriptionEndpoint: 'azureConnection'         # AzureRM connection
  kubernetesServiceConnection: 'aksConnection'         # Kubernetes-type connection
  k8sNamespace: 'default'
  manifestsPath: 'manifests/'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build & Push'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        options: '-DskipTests'
        javaHomeOption: 'JDK17'
        publishJUnitResults: false

    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)

- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy to Kubernetes'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Kubernetes@1
      displayName: 'Configure kubectl'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: '$(azureSubscriptionEndpoint)'
        azureResourceGroup: 'your-resource-group'       # 👈 update this
        kubernetesCluster: 'your-aks-cluster'           # 👈 update this
        command: 'login'
        useClusterAdmin: true

    - task: KubernetesManifest@0
      displayName: 'Deploy manifests to AKS'
      inputs:
        action: deploy
        kubernetesServiceConnection: '$(kubernetesServiceConnection)'
        namespace: '$(k8sNamespace)'
        manifests: |
          $(manifestsPath)/product-deployment.yaml
          $(manifestsPath)/product-service.yaml
        containers: |
          $(dockerImage)
