trigger:
  branches:
    include:
      - main

variables:
  dockerRegistryServiceConnection: 'acrproductservice'       # ✅ Must match your ACR service connection name
  imageRepository: 'product-service'
  containerRegistry: 'acrsringbootapp1.azurecr.io'
  dockerImage: '$(containerRegistry)/$(imageRepository):$(Build.BuildId)'
  azureSubscriptionEndpoint: 'azureConnection'               # ✅ Azure RM connection
  kubernetesServiceConnection: 'aksConnection'               # ✅ Kubernetes service connection
  k8sNamespace: 'default'
  manifestsPath: 'manifests'

stages:
# ---------------- Build Stage ----------------
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build & Push'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Checkout@1
      displayName: 'Checkout code'

    - task: Maven@4
      displayName: 'Build Spring Boot app with Maven'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false

    - task: Docker@2
      displayName: 'Build and Push Docker image to ACR'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'  # ✅ Using correct variable here
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'  # Adjust if your Dockerfile is nested
        tags: |
          $(Build.BuildId)

# ---------------- Deploy Stage ----------------
- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy to Kubernetes'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Kubernetes@1
      displayName: 'Configure kubectl'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: '$(azureSubscriptionEndpoint)'
        azureResourceGroup: 'springbootapp-rg'       # ✅ Replace with your RG name
        kubernetesCluster: 'k8ssringbootapp'         # ✅ Replace with your AKS cluster name
        command: 'login'
        useClusterAdmin: true

    - task: KubernetesManifest@0
      displayName: 'Deploy manifests to AKS'
      inputs:
        action: deploy
        kubernetesServiceConnection: '$(kubernetesServiceConnection)'
        namespace: '$(k8sNamespace)'
        manifests: '$(manifestsPath)/*.yaml'
        containers: |
          $(dockerImage)
