apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-gitgubactions
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service-gitgubactions
  template:
    metadata:
      labels:
        app: product-service-gitgubactions
    spec:
      containers:
        - name: product
          image: acrsuhi.azurecr.io/product-service-gitgubactions:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/products
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
